### PR TITLE
Custom Headers - Allow them to be enabled / disabled #164

### PR DESCRIPTION
**Pull request by ZubairGaj**

### CODE REVIEW

**Comment by cguedes** [comment]
@ZubairGaj I won't gonna merge this because this might not be the best way to implement this.
I will leave the issue #164 opened.

**Comment by behaghel** [comment]
Hey @cguedes, can you elaborate a bit more please? @ZubairGaj is determined to do the right thing but he needs more support from core maintainers. As a reminder, @ZubairGaj is full time on this repository trying to become proficient with the codebase and willing to take it to the next level.

Getting such a reaction where we close down his work without a great deal of explanation is not the best stewardship one can expect from internal open source. 

How can we be more efficient and constructive here? I really want to make this work.

**Comment by danielbcorreia** [comment]
Hi @behaghel, just to clarify as this may have not been the best choice of words:

@cguedes has been/is currently working on a change to API Explorer that needs to break some things, there are structural changes that need to be made in order for API Explorer to grow, to have it's dependencies up to date and also to be easier to maintain.

There are a couple of things that we need to change that conflict with some @ZubairGaj changes, however this code will of course be reused as soon as we have the structural changes done. The pull request is only being closed because this changes will need to be applied manually as the base version will be noticeably different.

I hope I cleared the reason for this, we don't want to get anyone upset especially since we are working towards the same goal! 😄

**Comment by behaghel** [comment]
That makes sense. Please keep @ZubairGaj posted! Structural changes interest him a lot as it's a great opportunity to get deep insight on the technical direction of this project. Thanks.

**Comment by cguedes** [comment]
Hi @behaghel. Thanks for the feedback.
As @danielbcorreia wrote, I'm in the middle of a big code refactor/reorganization to adopt Lerna, bump dependencies (code dept) and disregard others (ie. one that is being used in the custom headers section).

@ZubairGaj Sorry for not having written this. I thought you weren't actively working on this project. My bad.

I'm planning the have news next week.

**Pull request closed without merging**
